- name: create mjobs
  ansible.builtin.template:
    src: mjobs.xml
    dest: /tmp/mjobs.xml

- name: Create a jenkins - {{ item.job_name }}
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/mjobs.xml') }}"
    name: "{{ item.job_name}}"
    password: admin123
    url: http://172.31.22.116:8080
    user: admin

