- name: create mjobs
  ansible.builtin.template:
    src: sjobs.xml
    dest: /tmp/sjobs.xml

- name: Create a jenkins - {{ item.job_name }}
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/sjobs.xml') }}"
    name: "{{ item.job_name}}"
    password: admin123
    url: http://172.31.22.116:8080
    user: admin